Vagrant.configure("2") do |config|
  config.vm.box = "generic/bullsey64"
  config.vm.hostname = "pocopo.fjeclot.net"
  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "pocopo"
    v.memory = 2048
    v.cpus = 1
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']     
  end

  config.vm.network "public_network"

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8443

  config.vm.synced_folder ". ./codi", "/var/www/html"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    # sudo apt-get upgrade -y	
    sudo apt-get install -y aptitude
    sudo apt-get install -y net-tools
    sudo apt-get install -y apache2 apache2-doc
    sudo apt-get install -y libapache2-mod-php
    sudo apt-get install -y php7.4 
    sudo apt-get install -y mariadb-server mariadb-client
    sudo apt-get install -y composer
    sudo apt-get install -y php7.4-mysql
  SHELL

end
